Adding a command line tool to test poller monitors
The implementation class will use the current configured settings from
poller-configuration.xml, unless the user override them at run time.

$ /opt/opennms/bin/poller-test
usage: poller-test [options]
ERROR: Missing required options: i, s

 -c,--class <arg>       Monitor Class
 -i,--ipaddress <arg>   IP Address to test [required]
 -P,--package <arg>     Poller Package
 -p,--param <arg>       Service parameter ~ key=value
 -s,--service <arg>     Service name [required]