Include the list of parsers in the exception
Attempting to track down intermittent startup failures with the following stack trace:

An error occurred while attempting to start the "OpenNMS:Name=Telemetryd" service (class org.opennms.netmgt.daemon.SimpleSpringContextJmxServiceDaemon).  Shutting down and exiting.
javax.management.RuntimeMBeanException: java.lang.IllegalArgumentException: Each parser must be of type UdpParser but was not.
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.rethrow(DefaultMBeanServerInterceptor.java:829)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.rethrowMaybeMBeanException(DefaultMBeanServerInterceptor.java:842)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:811)
	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at org.opennms.netmgt.vmmgr.Invoker.invoke(Invoker.java:277)
	at org.opennms.netmgt.vmmgr.Invoker.invokeMethods(Invoker.java:206)
	at org.opennms.netmgt.vmmgr.Starter.start(Starter.java:157)
	at org.opennms.netmgt.vmmgr.Starter.startDaemon(Starter.java:95)
	at org.opennms.netmgt.vmmgr.Controller.start(Controller.java:173)
	at org.opennms.netmgt.vmmgr.Controller.main(Controller.java:150)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.opennms.bootstrap.Bootstrap$4.run(Bootstrap.java:531)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: Each parser must be of type UdpParser but was not.
	at org.opennms.netmgt.telemetry.listeners.factory.UdpListenerFactory.createBean(UdpListenerFactory.java:63)
	at org.opennms.netmgt.telemetry.listeners.factory.UdpListenerFactory.createBean(UdpListenerFactory.java:42)