Fix test classpath dependency issue:
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.127 s <<< FAILURE! - in org.opennms.netmgt.provision.persist.PersistenceSerializationTest
[ERROR] generateSchema(org.opennms.netmgt.provision.persist.PersistenceSerializationTest)  Time elapsed: 0.08 s  <<< ERROR!
javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
        at org.opennms.netmgt.provision.persist.PersistenceSerializationTest.setUp(PersistenceSerializationTest.java:126)
Caused by: java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory
        at org.opennms.netmgt.provision.persist.PersistenceSerializationTest.setUp(PersistenceSerializationTest.java:126)

[ERROR] generateXML(org.opennms.netmgt.provision.persist.PersistenceSerializationTest)  Time elapsed: 0.004 s  <<< ERROR!
javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
        at org.opennms.netmgt.provision.persist.PersistenceSerializationTest.setUp(PersistenceSerializationTest.java:126)
Caused by: java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory
        at org.opennms.netmgt.provision.persist.PersistenceSerializationTest.setUp(PersistenceSerializationTest.java:126)