Fixed all the hibernate managed entities, to avoid issues with JSON
The following annotation has been added on all entities managed by
hibertane with @XmlRootElement to avoid issues with the ReST API and
JSON:

@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})

Without that annotation, some exceptions are thrown into the WebUI when
requesting JSON data, for example:

org.codehaus.jackson.map.JsonMappingException: No serializer found for
class org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer and no
properties discovered to create BeanSerializer (to avoid exception,
disable SerializationConfig.Feature.FAIL_ON_EMPTY_BEANS) ) (through
reference chain: org.opennms.netmgt.model.OnmsEvent["nodeId"]->
org.opennms.netmgt.model.OnmsNode_$$_javassist_5["handler"])