Fix mock errors in JMXCollectorComplianceTest
org.opennms.core.xml.MarshallingResourceFailureException: Failed to marshal/unmarshal XML file while creating XML marshaller: javax.xml.bind.JAXBException:
Exception Description: The class org.mockito.internal.creation.bytebuddy.MockMethodInterceptor requires a zero argument constructor or a specified factory method.  Note that non-static inner classes do not have zero argument constructors and are not supported.
 - with linked exception:
[Exception [EclipseLink-50001] (Eclipse Persistence Services - 2.5.1.v20130918-f2b9fc5): org.eclipse.persistence.exceptions.JAXBException
Exception Description: The class org.mockito.internal.creation.bytebuddy.MockMethodInterceptor requires a zero argument constructor or a specified factory method.  Note that non-static inner classes do not have zero argument constructors and are not supported.]; nested exception is javax.xml.bind.JAXBException:
Exception Description: The class org.mockito.internal.creation.bytebuddy.MockMethodInterceptor requires a zero argument constructor or a specified factory method.  Note that non-static inner classes do not have zero argument constructors and are not supported.
 - with linked exception:
[Exception [EclipseLink-50001] (Eclipse Persistence Services - 2.5.1.v20130918-f2b9fc5): org.eclipse.persistence.exceptions.JAXBException
Exception Description: The class org.mockito.internal.creation.bytebuddy.MockMethodInterceptor requires a zero argument constructor or a specified factory method.  Note that non-static inner classes do not have zero argument constructors and are not supported.]
	at org.opennms.core.xml.MarshallingExceptionTranslator.translate(MarshallingExceptionTranslator.java:61)
	at org.opennms.core.xml.JaxbUtils.getMarshallerFor(JaxbUtils.java:345)
	at org.opennms.core.xml.JaxbUtils.marshal(JaxbUtils.java:178)
	at org.opennms.core.xml.JaxbUtils.marshal(JaxbUtils.java:117)
	at org.opennms.netmgt.collection.api.AbstractRemoteServiceCollector.lambda$marshalParameters$0(AbstractRemoteServiceCollector.java:92)
	at java.util.HashMap.forEach(HashMap.java:1288)
	at java.util.Collections$UnmodifiableMap.forEach(Collections.java:1505)
	at org.opennms.netmgt.collection.api.AbstractRemoteServiceCollector.marshalParameters(AbstractRemoteServiceCollector.java:71)
	at org.opennms.netmgt.collection.test.api.CollectorComplianceTest.canCollectUsingMinionWorkflow(CollectorComplianceTest.java:181)
        ...